apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  selector:
    app: weather-app
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: weathersecret
type: Opaque
stringData:
  API_KEY: #ADDAPIKEYHERE

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  selector:
    matchLabels:
      app: weather-app
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: weather-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: OW_API_KEY
          valueFrom:
            secretKeyRef:
              name: weathersecret
              key: API_KEY
