steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/weather-app', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/weather-app']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=weathersecret > secret.txt' ]
- name: 'bash'
  args: ['sed', '-i', 's/@@IMAGE_NAME@@/gcr.io\/$PROJECT_ID\/weather-app/g', 'k8s/deployment.yaml']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - 'run'
  - '--filename'
  - 'k8s/deployment.yaml'
  - '--image'
  - 'gcr.io/$PROJECT_ID/weather-app'
  - '--location'
  - 'europe-west2'
  - '--cluster'
  - 'default-cluster'
- name: 'gcr.io/cloud-builders/kubectl'
  id: DeploySecret
  args: ['create','secret','generic','weathersecret','--from-file=API_KEY=secret.txt']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west2'
  - 'CLOUDSDK_CONTAINER_CLUSTER=default-cluster'
